mysql:
    image: mysql:8.0.0
    environment:
        - MYSQL_ROOT_PASSWORD=dev
        - MYSQL_DATABASE=tipster
        - MYSQL_USER=tipster
        - MYSQL_PASSWORD=dev
    volumes:
        - /var/docker/mysql/tipster:/var/lib/mysql
nginx:
    image: nginx:1.11.5
    volumes:
        - ./:/app
        - /var/log/docker/nginx/optedif:/var/log/nginx
        - ./docker/nginx-conf:/etc/nginx/conf.d/default.conf
    links:
        - php:php
    ports:
        - 8032:80
    environment:
        - VIRTUAL_HOST=dev.tipster.fr
php:
    image: php:7.0-fpm
    volumes:
        - ./:/app
    links:
        - mysql:mysql
    working_dir: /app
adminer:
    image: clue/adminer
    environment:
        - VIRTUAL_HOST=dev.adminer.tipster.fr
    ports:
        - 8072:80
    links:
        - mysql:mysql
