<?php

namespace Tipster\FrontBundle\Entity\Repository;

/**
 * TipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipRepository extends \Doctrine\ORM\EntityRepository
{
}
